### PR TITLE
Switch from log4j to slf4j

### PR DESCRIPTION
**Pull request by ctrueden**

### CODE REVIEW

**Comment by bogovicj** [comment]
Thanks @ctrueden , will check this out tomorrow

**Comment by bogovicj** [comment]
I was getting this warning:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
which I'm not sure whether to be concerned about.

adding this 
```
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-simple</artifactId>
</dependency>
```
deals with it, though again, not sure what the warning is about.

**Comment by hanslovsky** [comment]
@bogovicj you do not need to be concerned about this warning. Libraries should generally only include `slf4j-api` but not a specific implementation. This leaves the logging choice up to the application that will eventually include the library as a dependency. If you want to resolve the warning for the test cases, you can include `slf4j-simple` as a test dependency:
```xml
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-simple</artifactId>
	<scope>test</test>
</dependency>
```

**Comment by ctrueden** [comment]
See also http://www.slf4j.org/faq.html#maven2

**Pull request merged**
